export const CATEGORY_IDS = {
  HEAD_HARMONY_CATEGORY_ID: 'KEBHZMN3NKI35R3KALVEIXF5',
  BODY_MASSAGE_CATEGORY_ID: 'SD6TLA6DBEJ55ANUMHAXCRCL',
  FOOT_CARE_CATEGORY_ID: 'NB4DPGUX6WKC2L7CQQGEH4N3',
  HEAD_SPA_CATEGORY_ID: 'WROTYNNNSDYVH24I2EYLHD7S',
  MANICURE_CATEGORY_ID: 'LN5V6F2ZWHNPEA5JBEHRCGZC'
};

export const CATEGORY_NAMES = {
  'KEBHZMN3NKI35R3KALVEIXF5': '🧘‍♀️ Head & Body Harmony Rituals',
  'SD6TLA6DBEJ55ANUMHAXCRCL': '💆 Body Massage Treatments',
  'NB4DPGUX6WKC2L7CQQGEH4N3': '💅 Foot Care',
  'WROTYNNNSDYVH24I2EYLHD7S': '💆‍♀️ Head Spa Treatments',
  'LN5V6F2ZWHNPEA5JBEHRCGZC': '💅 Manicure Services'
}
