import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Gift, Heart, MapPin, Phone, Sparkles, Star, Users } from 'lucide-react';
import PromotionPopup from '../components/PromotionPopup';

const features=[
  {title:'Chicago Head Spa',text:'Scalp care, steam, cleansing, massage, and deep quiet in one restorative ritual.',image:'/images/head.jpg',href:'/services/head-spa'},
  {title:'Massage & Bodywork',text:'Relaxation, deep tissue, hot stone, cupping, and thoughtful combinations.',image:'/images/bodyMassage.jpg',href:'/services/body-massage'},
  {title:'Nails & Foot Care',text:'Meticulous manicures, pedicures, and soothing care from fingertips to soles.',image:'/images/manicure.jpg',href:'/services/manicure'},
];
export default function Home(){return <><PromotionPopup/><div className="home-page">
  <section className="hero"><div className="hero-copy"><p className="eyebrow">A modern sanctuary in West Town</p><h1>Head Spa, Massage, Couples Services & Nails in Chicago.</h1><p className="hero-lead">Unhurried care from scalp to sole, designed around how you want to feel when you leave.</p><div className="flex flex-wrap gap-3"><Link className="button-primary" href="/services">Book now <ArrowRight size={17}/></Link><a className="button-secondary" href="tel:+13129003131"><Phone size={17}/> Call now</a></div><div className="hero-trust"><span><Star size={16} fill="currentColor"/> Loved by Chicago guests</span><span><MapPin size={16}/> 2706 W Chicago Ave</span></div></div><div className="hero-image"><Image src="/images/Firefly_Full-body spa ritual scene combining head and body massage. A tranquil environment wi 864039.jpg" alt="Relaxing head and body spa ritual at Sister Lavender Spa" fill priority sizes="(max-width: 900px) 100vw, 50vw"/></div></section>
  <section className="quick-actions"><Link href="/services"><Sparkles/>Book an appointment</Link><Link href="/gift-card"><Gift/>Buy a gift card</Link><Link href="/check-in"><Heart/>Guest check-in</Link><a href="https://maps.google.com/?q=2706+W+Chicago+Ave+Chicago+IL+60622" target="_blank" rel="noreferrer"><MapPin/>Directions</a></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Choose your ritual</p><h2>Care for every kind of day.</h2></div><Link href="/services">View services & pricing <ArrowRight size={16}/></Link></div><div className="feature-grid">{features.map(f=><article className="service-feature" key={f.title}><div className="service-feature-image"><Image src={f.image} alt={`${f.title} at Sister Lavender Spa`} fill sizes="(max-width: 768px) 100vw, 33vw"/></div><div className="p-5"><h3>{f.title}</h3><p>{f.text}</p><Link href={f.href}>Explore service <ArrowRight size={15}/></Link></div></article>)}</div></section>
  <section className="couples-section"><div><p className="eyebrow text-white/70">Better together</p><h2>Make space for two.</h2><p>Couples head spa and massage experiences let you slow down side by side—perfect for anniversaries, date days, and meaningful gifts.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/couples-services" className="button-light">Couples services</Link><Link href="/group-events" className="button-ghost-light"><Users size={17}/> Group events</Link></div></div></section>
  <section className="section rewards-band"><div><p className="eyebrow">Lavender Rewards</p><h2>Your self-care should give something back.</h2><p>Earn 1 point for every eligible service dollar. Redeem 500 points for $10 off.</p><Link href="/membership-rewards" className="button-secondary mt-5">Explore rewards <ArrowRight size={16}/></Link></div><div className="reward-orb"><b>500</b><span>points = $10 off</span></div></section>
  <section className="section"><div className="section-heading"><div><p className="eyebrow">Guest notes</p><h2>A little more relaxed than when they arrived.</h2></div></div><div className="review-grid">{['The head spa was incredibly relaxing and every detail felt thoughtful.','A beautiful couples experience. We felt cared for from start to finish.','Wonderful massage, kind staff, and such a calm space.'].map((r,i)=><blockquote key={r}><div className="stars">★★★★★</div><p>“{r}”</p><footer>Google guest review</footer></blockquote>)}</div><div className="mt-6 flex gap-4"><a className="text-link" href="https://www.google.com/search?q=Sister+Lavender+Spa+Chicago+reviews" target="_blank" rel="noreferrer">View more reviews</a><a className="text-link" href="https://www.google.com/search?q=Sister+Lavender+Spa+Chicago" target="_blank" rel="noreferrer">Leave a review</a></div></section>
  <section className="final-cta"><p className="eyebrow">Open daily · 9:30 AM–9:00 PM</p><h2>Your quiet hour is waiting.</h2><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/services" className="button-light">Book now</Link><Link href="/gift-card" className="button-ghost-light">Gift the experience</Link></div></section>
  </div></>}
